"""empty message

Revision ID: 455526718407
Revises: d947bd076a39
Create Date: 2020-07-20 04:19:29.662557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '455526718407'
down_revision = 'd947bd076a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=512), nullable=True))
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
